### ISSUE TITLE
Tried Configuring with SPring boot but not able to see the logs

### ISSUE THREAD

**Issue by DragonPulse** [rozidan/logger-spring-boot#1]

**Comment by rozidan** [comment]
I'll be happy to help, I'll need more information

**Comment by srikarrao** [comment]
Unable to fetch compile 'com.github.rozidan:logger-spring-boot:1.0.0-SNAPSHOT' from the maven repository.
Couldn't find the library under https://jcenter.bintray.com/com/github/rozidan/.

**Comment by rozidan** [comment]
readme.md has been changed, please add the  "https://oss.sonatype.org/content/groups/public"  repository

**Comment by rozidan** [comment]
readme.md has been changed
