### ISSUE TITLE
Pom File dependency not working

### ISSUE THREAD

**Issue by sharmmoh1983** [rozidan/logger-spring-boot#2]
```
<dependency>
    <groupId>com.github.rozidan</groupId>
    <artifactId>logger-spring-boot</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
```

**Comment by ralphavalon** [comment]
Have you added the following repository?

> <repositories>
        <repository>
            <id>sonatype-oss-public</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
